name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: src

    steps:
      - uses: actions/checkout@v2

      - name: Clean Qt dir
        run: rm -rf '${{ github.workspace }}/Qt'

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          dir: '${{ github.workspace }}/Qt'

      - name: cmake
        run: cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/5.15.2/gcc_64' .

      - name: make all targets
        run: make all

      - name: UT for BtsApplication
        run: make BtsApplicationUT

      - name: run BTS ut
        run: ./BTS/Tests/Application/BtsApplicationUT

      - name: UT for COMMON
        run: make COMMON_UT

      - name: UT for UeApplication
        run: make UeApplicationUT

      - name: Next Steps
        run: echo "Add your next steps here"
